"""
Spotify playlist builder — OAuth via spotipy, idempotent playlist creation.
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone

import spotipy
from spotipy.oauth2 import SpotifyOAuth

from config import (
    SPOTIFY_CLIENT_ID,
    SPOTIFY_CLIENT_SECRET,
    SPOTIFY_REDIRECT_URI,
    SPOTIFY_SCOPE,
)
from graph import queries


def _get_client() -> spotipy.Spotify:
    auth = SpotifyOAuth(
        client_id=SPOTIFY_CLIENT_ID,
        client_secret=SPOTIFY_CLIENT_SECRET,
        redirect_uri=SPOTIFY_REDIRECT_URI,
        scope=SPOTIFY_SCOPE,
        cache_path=".spotify_cache",
    )
    return spotipy.Spotify(auth_manager=auth)


def _find_artist_id(sp: spotipy.Spotify, band_name: str) -> str | None:
    results = sp.search(q=f"artist:{band_name}", type="artist", limit=1)
    items = results.get("artists", {}).get("items", [])
    return items[0]["id"] if items else None


def _get_top_tracks(sp: spotipy.Spotify, artist_id: str, limit: int = 5) -> list[str]:
    result = sp.artist_top_tracks(artist_id, country="US")
    return [t["uri"] for t in result.get("tracks", [])[:limit]]


def _playlist_fingerprint(band_ids: list[str], filters: dict) -> str:
    key = "|".join(sorted(band_ids)) + str(sorted(filters.items()))
    return hashlib.sha256(key.encode()).hexdigest()[:12]


def build_playlist(
    band_ids: list[str],
    playlist_name: str | None = None,
    filters: dict | None = None,
    tracks_per_band: int = 5,
) -> str:
    """
    Build a Spotify playlist from a list of Band node IDs.

    Returns the Spotify playlist URL.
    """
    filters = filters or {}
    sp = _get_client()
    user_id = sp.me()["id"]

    if not playlist_name:
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        playlist_name = f"Festival Radar — {date_str}"

    fingerprint = _playlist_fingerprint(band_ids, filters)
    description = f"Auto-generated by Festival Tracker | id:{fingerprint}"

    # Idempotency check — look for existing playlist with same fingerprint
    existing_id = _find_existing_playlist(sp, user_id, fingerprint)

    # Collect track URIs
    track_uris: list[str] = []
    for band_id in band_ids:
        band = queries.get_band(band_id)
        if not band:
            continue

        # Use stored Spotify ID or search
        spotify_id = band.get("spotify_id") or ""
        if not spotify_id:
            spotify_id = _find_artist_id(sp, band["name"]) or ""
            if spotify_id:
                queries.upsert_band(band["name"], spotify_id=spotify_id)

        if not spotify_id:
            continue

        tracks = _get_top_tracks(sp, spotify_id, limit=tracks_per_band)
        track_uris.extend(tracks)

    if existing_id:
        # Replace tracks in existing playlist (idempotent)
        sp.playlist_replace_items(existing_id, track_uris[:100])
        playlist_id = existing_id
    else:
        pl = sp.user_playlist_create(
            user=user_id,
            name=playlist_name,
            public=True,
            description=description,
        )
        playlist_id = pl["id"]
        # Spotify add_items max 100 per call
        for i in range(0, len(track_uris), 100):
            sp.playlist_add_items(playlist_id, track_uris[i : i + 100])

    return f"https://open.spotify.com/playlist/{playlist_id}"


def _find_existing_playlist(
    sp: spotipy.Spotify, user_id: str, fingerprint: str
) -> str | None:
    offset = 0
    while True:
        result = sp.user_playlists(user_id, limit=50, offset=offset)
        items = result.get("items", [])
        for pl in items:
            if pl and fingerprint in (pl.get("description") or ""):
                return pl["id"]
        if not result.get("next"):
            break
        offset += 50
    return None


def filter_band_ids(
    rating_filter: int | None = None,
    interest_filter: list[str] | None = None,
    bubble_filter: list[str] | None = None,
    festival_id: str | None = None,
    person_name: str = "default",
) -> list[str]:
    """
    Return band IDs matching the given filters.

    Args:
        rating_filter: minimum score (inclusive).
        interest_filter: list of interest levels to include.
        bubble_filter: list of bubble statuses to include.
        festival_id: if provided, only bands that played this festival.
        person_name: whose ratings to check.
    """
    all_bands = queries.list_bands()

    if festival_id:
        timeline = queries.get_full_timeline()
        festival_band_ids = {
            row["b.id"] for row in timeline if row.get("f.id") == festival_id
        }
        all_bands = [b for b in all_bands if b["id"] in festival_band_ids]

    if bubble_filter:
        all_bands = [b for b in all_bands if b.get("bubble_status") in bubble_filter]

    if rating_filter is not None or interest_filter:
        ratings = {
            r["b.id"]: r
            for r in queries.get_all_ratings(person_name)
        }
        filtered = []
        for band in all_bands:
            r = ratings.get(band["id"])
            if rating_filter is not None:
                if not r or (r.get("r.score") or 0) < rating_filter:
                    continue
            if interest_filter:
                if not r or r.get("r.interest") not in interest_filter:
                    continue
            filtered.append(band)
        all_bands = filtered

    return [b["id"] for b in all_bands]
